CREATE TABLE IF NOT EXISTS ADMIN(
	`username` VARCHAR(20) NOT NULL,
	`password` VARCHAR(20) NOT NULL,
	PRIMARY KEY(`username`)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ERROR(
	`msg` VARCHAR(255)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS SOCIETA(
	`nome`					VARCHAR(25) NOT NULL,
	PRIMARY KEY(`nome`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PALESTRA(
	`indirizzo`				VARCHAR(50) NOT NULL,
	`nome`					VARCHAR(25) NOT NULL,
	`capienza`				SMALLINT UNSIGNED,
	PRIMARY KEY(`indirizzo`)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS ARBITRO(
	`CF`					CHAR(16) NOT NULL,
	`nome`					VARCHAR(25) NOT NULL,
	`cognome`				VARCHAR(25) NOT NULL,
	PRIMARY KEY(`CF`)	
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS SQUADRA(
	`nome` 					VARCHAR(25) NOT NULL,
	`societa`				VARCHAR(25),
	`indirizzoPal`			VARCHAR(50),
	PRIMARY KEY(`nome`),
	FOREIGN KEY(`societa`)
	REFERENCES SOCIETA(`nome`)
	ON DELETE SET NULL 
	ON UPDATE CASCADE,
	FOREIGN KEY(`indirizzoPal`)
	REFERENCES PALESTRA(`indirizzo`)
	ON DELETE SET NULL 
	ON UPDATE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS GIOCATORE(
	`CF`					CHAR(16) NOT NULL,
	`nome` 					VARCHAR(25) NOT NULL,
	`cognome` 				VARCHAR(25) NOT NULL,
	`indirizzo` 			VARCHAR(50),
	`ingaggio` 				INT UNSIGNED,
	`ruoloPreferito`		VARCHAR(20),
	`squadra` 				VARCHAR(25),
	PRIMARY KEY(`CF`),
	FOREIGN KEY(`squadra`) REFERENCES SQUADRA(`nome`)
	ON DELETE SET NULL ON UPDATE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS UTENTE(
	`username` VARCHAR(20) NOT NULL,
	`password` VARCHAR(20) NOT NULL,
	`CodFisc`  CHAR(16),
	PRIMARY KEY(`username`),
	FOREIGN KEY(`CodFisc`) REFERENCES GIOCATORE(`CF`)
	ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PERSONALESQUADRA(
	`CF`					CHAR(16) NOT NULL,
	`nome`					VARCHAR(25) NOT NULL,
	`cognome`				VARCHAR(25) NOT NULL,
	`Ruolo`					ENUM('manager','allenatore','presidente'),
	`squadra` 				VARCHAR(25),
	PRIMARY KEY (`CF`),
	FOREIGN KEY(`squadra`) REFERENCES SQUADRA(`nome`)
	ON DELETE SET NULL ON UPDATE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PARTITAGIOCATA(
	`id`					INT UNSIGNED,
	`data`					DATE NOT NULL,
	`locali`				VARCHAR(25) NOT NULL,
	`ospiti`				VARCHAR(25) NOT NULL,
	`palestra`				VARCHAR(50) NOT NULL,
	`arbitro`				CHAR(16) NOT NULL,
	`setLocali`				SMALLINT UNSIGNED NOT NULL,
	`setOspiti` 			SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`locali`) REFERENCES SQUADRA(`nome`),
	FOREIGN KEY(`ospiti`) REFERENCES SQUADRA(`nome`),
	FOREIGN KEY(`arbitro`) REFERENCES ARBITRO(`CF`)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`palestra`) REFERENCES PALESTRA(`indirizzo`)
	ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PARTITADAGIOCARE(
	`id`					INT UNSIGNED,
	`data`					DATE NOT NULL,
	`locali`				VARCHAR(25) NOT NULL,
	`ospiti`				VARCHAR(25) NOT NULL,
	`palestra`				VARCHAR(50) NOT NULL,
	`arbitro`				CHAR(16) NOT NULL,
	PRIMARY KEY(`id`),
	FOREIGN KEY(`locali`) REFERENCES SQUADRA(`nome`)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`ospiti`) REFERENCES SQUADRA(`nome`)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`arbitro`) REFERENCES ARBITRO(`CF`)
	ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY(`palestra`) REFERENCES PALESTRA(`indirizzo`)
	ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS CLASSIFICA(
	`squadra`				VARCHAR(25) NOT NULL,
	`punteggio`				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`pGiocate`				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`pVinte` 				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`pPerse`				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`setVinti`				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`setPersi`				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(`squadra`),
	FOREIGN KEY(`squadra`) REFERENCES SQUADRA(`nome`)
	ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = InnoDB;
